name: Deploy Weather app js client

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    name: Deploy Weather app js client
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # - name: Build Docker Image
      #   uses: docker/build-push-action@v4
      #   with:
      #     context: .
      #     dockerfile: Dockerfile
      #     push: false
      #     tags: ${{ secrets.DOCKER_HUB_USERNAME }}/weather-app-view:latest

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCEESS_TOKEN }}

      - name: Push to Docker Hub
        uses: docker/build-push-action@v4
        with:
          context: .
          dockerfile: Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/weather-app-view:latest